name: Backup Data

on:
  schedule:
    - cron: "0 * * * *"  # запуск каждый час (в начале часа)
  workflow_dispatch:  # запуск вручную

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name github-actions
          git config user.email actions@github.com

      - name: Commit data.json
        run: |
          git add data.json
          git commit -m "Auto-backup data.json"
          git push || echo "Nothing to commit"
